M48
; DRILL file {KiCad 8.0.8} date 2025-12-16T16:03:16-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-16T16:03:16-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,8,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.250
%
G90
G05
T1
X75.5Y-87.25
X75.5Y-97.25
X78.0Y-87.25
X78.0Y-97.25
X83.0Y-92.25
T2
X83.89Y-57.12
X83.89Y-62.12
T3
X84.26Y-101.475
X84.26Y-112.905
M30
